window:
  padding:
    x: 10
    y: 10

font:
  normal:
    family: JetbrainsMono Nerd Font

  size: 12.5

colors:
  primary:
    background: "#121212"
    foreground: "#f8f8f2"
  normal:
    black:   "#121212"
    red:     "#f92672"
    green:   "#a6e22e"
    yellow:  "#fd971f"
    blue:    "#66d9ef"
    magenta: "#9e6ffe"
    cyan:    "#5e7175"
    white:   "#ccccc6"
  bright:
    black:   "#1b1d1e"
    red:     "#ff669d"
    green:   "#beed5f"
    yellow:  "#e6db74"
    blue:    "#66d9ef"
    magenta: "#9e6ffe"
    cyan:    "#a3babf"
    white:   "#f8f8f2"
